development: &non_production_settings
  site_url: http://localhost:3000
  site_name: sdwaterwatch.org
  admin_email: admin@sdwaterwatch.org
  noreply_email: no-reply@sdwaterwatch.org
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.sdwaterwatch.org
  site_name: sdwaterwatch.org
  admin_email: admin@sdwaterwatch.org
  noreply_email: no-reply@sdwaterwatch.org
  
production:
  site_url: http://www.sdwaterwatch.org
  site_name: sdwaterwatch.org
  admin_email: admin@sdwaterwatch.org
  noreply_email: no-reply@sdwaterwatch.org
